import psycopg as postgres
import os

URL_DATABASE = os.environ.get("URL_DATABASE")


def get_connect():
    if not URL_DATABASE:
        raise ConnectionError("URL_DATABASE is not set")
    return postgres.connect(URL_DATABASE)


def create_table():
    connect = get_connect()
    cursor = connect.cursor()
    cursor.execute(
        """CREATE TABLE IF NOT EXISTS shop_owner(
            id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
            name VARCHAR(100) NOT NULL,
            email TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL
            )"""
    )
    cursor.execute(
        """CREATE TABLE IF NOT EXISTS product(
        id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        name VARCHAR(100)NOT NULL,
        PRICE DECIMAL(10, 2)NOT NULL,
        QUANTITY INT,
        shop_owner_id INT REFERENCES shop_owner(id)
        )"""
    )
    cursor.execute(
        """CREATE TABLE IF NOT EXISTS sale(
        id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        quantity_sold INT NOT NULL,
        total_price DECIMAL(10,2) NOT NULL,
        date_sale TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        product_id int REFERENCES product(id),
        shop_owner_id int REFERENCES shop_owner(id)
        )"""
    )

    connect.commit()
    cursor.close()
    connect.close()


def register_account(name, email, password_hash):
    connect = get_connect()
    cursor = connect.cursor()
    cursor.execute("""SELECT 1 FROM shop_owner WHERE email = %s LIMIT 1""", (email,))
    result = cursor.fetchone()
    exists = result is not None
    if exists:
        print("Email already exists")
        cursor.close()
        connect.close()
        return True
    else:
        cursor.execute(
            "INSERT INTO shop_owner (name, email, password) VALUES (%s, %s, %s)",
            (name, email, password_hash),
        )
        print("Email registred!")
        connect.commit()
        cursor.close()
        connect.close()
        return False
